Device label must be specified when generating ISO

diff --git a/subsets/bind-build b/subsets/bind-build
--- a/subsets/bind-build
+++ b/subsets/bind-build
@@ -1,5 +1,5 @@
 declare\
-  _in= _out= _cookbook=
+  _in= _out= _cookbook= _label=
   _interactive=false
   _aufs=false
   _generate=false
@@ -9,12 +9,13 @@ declare\
   _arch=$(uname -m) # The target architecture
   _shell=/bin/zsh   # The default shell on chroot
 
-while getopts i:o:c:s:tnufgqa: opt; do
+while getopts l:i:o:c:s:tnufgqa: opt; do
   case $opt in
     i) _in=$OPTARG ;;
     o) _out=$OPTARG ;;
     c) _cookbook=$OPTARG ;;
     s) _shell=$OPTARG ;;
+    l) _label=$OPTARG ;;
     t) _interactive=true ;;
     n) _aufs=true ;;
     u) _update=true ;;
@@ -33,5 +34,10 @@ fi
 
 if [ $_generate = true ] && [[ -z $_out ]]; then
   echo "Remastered ISO path is required."
+  exit 1
+fi
+
+if [ $_generate = true ] && [[ -z $_label ]]; then
+  echo "Device label is required."
   exit 1
 fi
